# Generated by Django 4.0.1 on 2022-03-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacelearn', '0002_remove_profile_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_programming_lang',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
